### ISSUE TITLE
About directory routing

### ISSUE THREAD

**Issue by Xiaozeeze** [ajgallego/document-image-binarization#33]
Can you tell me about the data set path arrangement? (such as the PHI dataset)
Thanks!

**Comment by ajgallego** [comment]
The dataset path arrangement is defined at the function "load_dataset_folds", which is in the "train.py" file.

When running this code you have to set the -path parameter with the folder that contains the datasets and use -db to set the dataset name.

I hope this helps

**Comment by Xiaozeeze** [comment]
Is that what you mean？
path/db/dbp

I define path as datasets, and db in "phi" is "PHI/train/phi_GR", so my directory is "datasets/PHI/train/phi_GR", right? 
And in this directory, there are two subfolders with the suffix GR and GT, which contain the original image and the fine standard respectively.

Am I doing the right thing?

**Comment by Xiaozeeze** [comment]
I did this but made a mistake.

Traceback (most recent call last):
  File "train.py", line 305, in <module>
    main()
  File "train.py", line 252, in main
    x_test, y_test = utilDataGenerator.generate_chunks(array_test_files, x_sufix, y_sufix, args.window, args.window)
  File "/public/home/***/***/document-image-binarization-master/binarize/utilDataGenerator.py", line 74, in generate_chunks
    x_data = x_data.reshape(x_data.shape[0], x_data.shape[1], x_data.shape[2], 1)
IndexError: tuple index out of range

After that, I deleted two subfolders with the suffix GR and GT, and this error also occurred, so I think it maybe  a path error.

**Comment by ajgallego** [comment]
Yes, that is right. The path should be: 
datasets/PHI/train/phi_GR
datasets/PHI/train/phi_GT
datasets/PHI/test/phi_GR
datasets/PHI/test/phi_GT

And you should run something like this:
python -u train.py -path datasets -db phi ...rest of parameters...

The extensions of the images should be ".png"

You may also add some prints in the code to debug what is happening.

**Comment by Xiaozeeze** [comment]
Thanks！ My problem has been solved！Also, I trained with my own data set, and it worked well.

Finally,can you tell me about dbp, if you like?

**Comment by ajgallego** [comment]
"-dbp" parameter is only used for the datasets Dibco and Palm. 
It allows you to indicate the fold number of Dibco and the GT number of Palm. 
In Dibco there are datasets for several years skipped from 2009 to 2016, so you can enter dbp values from 0 to 6 to select the year you want.
On Palm there are 2 annotators, so with dbp you can enter 0 to select the first annotator and 1 for the second.
